### ISSUE TITLE
Run MetaSEM on new dataset

### ISSUE THREAD

**Issue by jonathan-f** [ZhangLab312/MetaSEM#1]
Hello,
I would like to use MetaSEM in my research, using the GRN inference task on a new single-cell RNA-seq dataset, without a ground truth network. 

I tried to run the code in MetaSEM_main.py  but it looks to me that:

- the parameters taken as input by the script do not correspond to those assigned at lines 36-38 (opt.cell, opt.tsv_path, opt.input_path). 

- there is not an option to run MetaSEM_main.py without a ground truth net.

Could you provide guidance on how to run MetaSEM on a new dataset?

Thank you,
Best wishes
Jonathan

**Comment by ZhangLab312** [comment]
Hi Jonathan,

Good day,
 
Thank you for taking attention to our tools. We have already updated the script on Github.
 
We make the following response to your problem:
 
1)&nbsp;&nbsp;&nbsp; .We updated the definition of some parameters.
 
“tsv_path”: This parameter represents the storage path of GRN file. In this tsv file, some regulatory weights deduced from the model are stored.
 
“input_path”: The input scRNA-seq gene expression file.
 
“net_path”: This parameter represents the storage path of the ground truth network file.
 
&nbsp;
 
2)&nbsp;&nbsp;&nbsp; The function of inference GRN without ground truth network.
 
Our method can not directly run the dateset without ground truth network. This option would be realized in our next work. Here , we provide some alternatives.
 
Ø&nbsp; Following the workflow of <Benchmarking algorithms for gene regulatory network inference from single-cell transcriptomic data&gt; (https://doi.org/10.1038/s41592-019-0690-6).
 
Ø&nbsp; Also you can use GENIE3 or GRNBoost2 to construct the ground truth network.
 
3)&nbsp;&nbsp;&nbsp; The guidance on how to run the MetaSEM on a new dataset:
 
Firstly, it is necessary to make sure your dataset is sorted out by some prior knowledge. In our paper, we used standard deviation to clear up the data. The dataset was stored in matrices with the vertical axis gene expression and the sample as the horizontal axis. 
 
Secondly, build the ground truth network based on the filtered data. In this csv file, the genes in the first column regulate the genes in the second column. Each row represents an edge.
 
Thirdly, please follow the contents of Turtorial.ipynb to run the program.
 
&nbsp;
 
Thank you for considering our tools again.
 
Sincerely,
 
Yongqing Zhang
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZhangLab312/MetaSEM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月8日(星期三) 晚上8:32
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ZhangLab312/MetaSEM] Run MetaSEM on new dataset (Issue #1)





 
Hello,
 I would like to use MetaSEM in my research, using the GRN inference task on a new single-cell RNA-seq dataset, without a ground truth network.
 
I tried to run the code in MetaSEM_main.py  but it looks to me that:
  
 
the parameters taken as input by the script do not correspond to those assigned at lines 36-38 (opt.cell, opt.tsv_path, opt.input_path).
 
 
 
there is not an option to run MetaSEM_main.py without a ground truth net.
 
  
Could you provide guidance on how to run MetaSEM on a new dataset?
 
Thank you,
 Best wishes
 Jonathan

**Comment by jonathan-f** [comment]
Dear Yongqing,
thank you very much for the explanations.

Best wishes 
Jonathan
